version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=projekt-mohammad.ddns.net
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://45.151.122.162:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./.env
    command:
      - start-dev
      - --proxy=passthrough

  frontend:
    build: frontend
    image: frontend
    container_name: frontend
    ports:
      - 4200:4200
