name: Backend Pipeline

on:
  push:
    branches: [ "master" ]
    paths:
    - "backend/**"
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
          java-version: 1.17
    - name: Build with Maven
      working-directory: ./backend
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      working-directory: ./backend
      run: mvn -B test --file pom.xml

  build:
    needs: [test]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: backend
      run: sudo docker image prune -f
    - name: compose build
      working-directory: ./deployment
      run: sudo docker-compose build backend
    - name: compose up
      working-directory: ./deployment
      run: sudo docker-compose up -d backend
