name: E2E pipeline
on:
  push:
    branches: [ "master" ]
    paths: 
      - './e2e'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
 build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Image prune
        run: sudo docker image prune -f
      - name: docker build
        working-directory: ./deployment
        run: sudo docker-compose build e2e
      - name: docker-compose up
        working-directory: ./deployment
        run: sudo docker-compose up -d e2e
